name: Manual and Scheduled Workflows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      logLevel:
        description: 'Log level for this run'
        required: false
        default: 'info'
